name: "Medium Blogs"
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout local repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
          bundler-cache: true

      - name: Import blogs from Medium
        run: bundle exec jekyll import medium --username machiavellli

      - name: Push
        run: |
          git add _posts
          if ! (git diff --staged --quiet --exit-code); then
              git config --global user.name "GitHub Actions"
              git commit -m 'Mediuming'
          fi
          git push origin main
